apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment-canaryv2
spec:
 template:
   metadata:
     labels:
       app: nginx
   spec:
    containers:
    - name: nginx-container
      image: nginx:1.9.1
 replicas: 2
 selector:
    matchLabels:
      app: nginx