apiVersion: v1
kind: Pod
metadata:
  name: secret-vol
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "ls /etc/config/" ]
      volumeMounts:
      - name: config-secret
        mountPath: /etc/config
  volumes:
    - name: config-secret
      secret:
        secretName: my-secret
  restartPolicy: Never