apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: my-secret
  restartPolicy: Never
