apiVersion: v1
kind: Pod
metadata:
 name: small
spec:
 containers:
 - name: data-processor
   image: nginx
 affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: NotIn
            values: 
            - large
            - medium
