apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: pod-reader-clusterrolebinding-group
subjects:
- kind: Group
  name: Manager # Name is case sensitive
#  apiGroup: rbac.authorization.k8s.io
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader-clusterrole
  apiGroup: rbac.authorization.k8s.io
