apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-master-binding-ns1
  namespace: namespace1
subjects:
- kind: ServiceAccount
  name: sa
  namespace: default
roleRef:
  kind: ClusterRole 
  name: job-master
  apiGroup: rbac.authorization.k8s.io
